[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'vim-closetag'
